NombreFoto='dataset/Source Images/Training sets/01-XX-03.jpg';
SalidaFoto='Resultados/01-XX-03.png';
%[DatosEntradaPaper]=LecturaImagenCompleta(NombreFoto);
%ClassRN(net,x_ga_opt,DatosEntradaPaper,NombreFoto,SalidaFoto);
NombreFoto='dataset/Source Images/Training sets/02-XX-03.jpg';
SalidaFoto='Resultados/02-XX-03.png';
%[DatosEntradaPaper]=LecturaImagenCompleta(NombreFoto);
%ClassRN(net,x_ga_opt,DatosEntradaPaper,NombreFoto,SalidaFoto);
NombreFoto='dataset/Source Images/Training sets/04-XX-03.jpg';
SalidaFoto='Resultados/04-XX-03.png';
%[DatosEntradaPaper]=LecturaImagenCompleta(NombreFoto);
%ClassRN(net,x_ga_opt,DatosEntradaPaper,NombreFoto,SalidaFoto);
NombreFoto='dataset/Source Images/Training sets/05-XX-03.jpg';
SalidaFoto='Resultados/05-XX-03.png';
%[DatosEntradaPaper]=LecturaImagenCompleta(NombreFoto);
%ClassRN(net,x_ga_opt,DatosEntradaPaper,NombreFoto,SalidaFoto);
NombreFoto='dataset/Source Images/Training sets/09-XX-05.jpg';
SalidaFoto='Resultados/09-XX-05.png';
[DatosEntradaPaper]=LecturaImagenCompleta(NombreFoto);
ClassRN(net,x_ga_opt,DatosEntradaPaper,NombreFoto,SalidaFoto);
NombreFoto='dataset/Source Images/Test sets/03-XX-01.jpg';
SalidaFoto='Resultados/03-XX-01.png';
[DatosEntradaPaper]=LecturaImagenCompleta(NombreFoto);
ClassRN(net,x_ga_opt,DatosEntradaPaper,NombreFoto,SalidaFoto);