CarpetaTest='dataset/Test sets/E-01/';
[TestCompleto,EtiquetasCompleta]=Lectura(CarpetaTest);
TestRN(net,x_ga_opt,TestCompleto,EtiquetasCompleta);
display('*****************************');
CarpetaTest='dataset/Test sets/E-02/';
[TestCompleto,EtiquetasCompleta]=Lectura(CarpetaTest);
TestRN(net,x_ga_opt,TestCompleto,EtiquetasCompleta);
display('*****************************');
CarpetaTest='dataset/Test sets/E-03/';
[TestCompleto,EtiquetasCompleta]=Lectura(CarpetaTest);
TestRN(net,x_ga_opt,TestCompleto,EtiquetasCompleta);
display('*****************************');
CarpetaTest='dataset/Test sets/E-04/';
[TestCompleto,EtiquetasCompleta]=Lectura(CarpetaTest);
TestRN(net,x_ga_opt,TestCompleto,EtiquetasCompleta);
display('*****************************');
CarpetaTest='dataset/Test sets/E-05/';
[TestCompleto,EtiquetasCompleta]=Lectura(CarpetaTest);
TestRN(net,x_ga_opt,TestCompleto,EtiquetasCompleta);
display('*****************************');
CarpetaTest='dataset/Test sets/G-01/';
[TestCompleto,EtiquetasCompleta]=Lectura(CarpetaTest);
TestRN(net,x_ga_opt,TestCompleto,EtiquetasCompleta);
display('*****************************');
CarpetaTest='dataset/Test sets/G-02/';
[TestCompleto,EtiquetasCompleta]=Lectura(CarpetaTest);
TestRN(net,x_ga_opt,TestCompleto,EtiquetasCompleta);
display('*****************************');
CarpetaTest='dataset/Test sets/G-03/';
[TestCompleto,EtiquetasCompleta]=Lectura(CarpetaTest);
TestRN(net,x_ga_opt,TestCompleto,EtiquetasCompleta);
display('*****************************');
CarpetaTest='dataset/Test sets/G-04/';
[TestCompleto,EtiquetasCompleta]=Lectura(CarpetaTest);
TestRN(net,x_ga_opt,TestCompleto,EtiquetasCompleta);
display('*****************************');
CarpetaTest='dataset/Test sets/G-05/';
[TestCompleto,EtiquetasCompleta]=Lectura(CarpetaTest);
TestRN(net,x_ga_opt,TestCompleto,EtiquetasCompleta);
display('*****************************');